<a href="https://colab.research.google.com/github/MonsterHorn/MachineLearning/blob/main/Google_Colab_%E7%9A%84%E4%BD%BF%E7%94%A8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Google Colab 的使用

## 1. 安装依赖

前面加 `!` 可以执行`Linux`指令




In [ ]:
!pwd


## 2. 运行环境

 `代码执行程序 -> 运行时类型 ` , 更改为 GPU ， 运行下面的代码进行测试：

In [4]:
import torch
import numpy as np
torch.cuda.is_available()

True

# Pytorch 的使用

## 1. Tensor 的使用

### 1.1 生成 Tensor 

1. 从 list/NumPy 中生成一个 Tensor

2. 全 0 的 Tensor
3. 全 1 的 Tensor

In [5]:
# 1. 数组 --> Tensor 
x1 = torch.tensor([[1,-1],[-1,1]])
# 2. NumPy --> Tensor 
x2 = torch.from_numpy(np.array([[1,-1],[-1,1]]))
# 3. 全 0 Tensor 
x3 = torch.zeros([2,2])
# 4. 全 1 Tensor 
x4 = torch.ones([1,2,5])

print(x1)
print(x2)
print(x3)
print(x4)

tensor([[ 1, -1],
        [-1,  1]])
tensor([[ 1, -1],
        [-1,  1]])
tensor([[0., 0.],
        [0., 0.]])
tensor([[[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]])


### 1.2  Tensor 的操作
1. Squeeze  去掉一维
2. Unsqueeze 展开维度
3. Transpose 矩阵转置
4. Cat    Tensor的拼接 
5. Pow    次方
6. Sum    加总
7. Mean    均值

In [ ]:
x5 = torch.zeros([1,2,3]) # 创建一个 三维 的 Tensor
x5 = x5.squeeze(0)     # 1. 删除 0 维
x5 = x5.unsqueeze(1)    # 2. 添加 1 维
x5 = x5.transpose(0,1)   # 3. 交换两个维度


x6 = torch.zeros([2,1,3]) # 创建一个 三维 的 Tensor
x7 = torch.zeros([2,2,3]) # 创建一个 三维 的 Tensor
x8 = torch.zeros([2,3,3]) # 创建一个 三维 的 Tensor
x9 = torch.cat([x6,x7,x8],dim=1) # 4. 按照 1 维 进行拼接
x9.shape


### 1.3 计算梯度

使用`backward`函数计算梯度。 y.backward() 


In [3]:
x10 = torch.tensor([[1.,0.],[-1.,1.]],requires_grad=True)
y = x10.pow(2).sum()
y.backward()    # 反向计算梯度
x10.grad      # 查看梯度值

tensor([[ 2.,  0.],
        [-2.,  2.]])

### 1.4 加载数据


In [ ]:
from torch.utils.data import Dataset, DataLoader

class MyDataset(Dataset):
    # 1. 加载数据
    def _init_(self,file):
        self.data = ...
    # 2. 获取数据
    def _getitem_(self,index):
        return self.data[index]
    # 3. 获取数据大小
    def _len_(self):
        return len(self.data)

dataset = MyDataset(file)
dataloader = DataLoader(dataset,batch_size,shuffle=True) # shuffle是否洗牌； Training（训练）True; Testing（测试）False

### 1.5 建立模型

线性层（全连接层）
w * x + b = y

```python
layer = torch.nn.Liner(in_features,out_features)
layer.weight.shape # 权重的形状
layer.bias.shape  # 偏移的形状

```

In [ ]:
import torch.nn as nn
class MyModel(nn.Moduel):
    def _init_(self):
        super(MyModel,self)._init_()
        self.net = nn.Sequential(
            nn.Linear(10,32),
            nn.Sigmoid(),
            nn.Linear(32,1)
        )
        
    def forward(self,x):
        return self.net(x)

### 1.6 损失函数

- 方差均值损失（Mean Squared Error）[线性回归]

```python
nn.MSELoss()
```

- 交叉熵损失（Cross Entropy）[分类]

```python
nn.CrossEntropyLoss()
```


## 1.7 优化器

```python
torch.optim.SGD(params,lr,momentum=0)
```

### 1.8 参数保存与加载
```python
# 保存
torch.save(model.state_dict(),path)

# 加载
ckpt=torch.load(path)
model.state_dict(ckpt)
```

### 1.8 总结



In [ ]:
dataset = MyDataset(file) # 加载数据
tr_set = DataLoader(dataset,16,shuffle=True) # 构建训练集 shuffle是否洗牌； Training（训练）True; Testing（测试）False
model = MyModel().to(device) # 创建模型
criterion = nn.MSELoss() # 定义损失计算方法
optimizer = torch.optim.SGD(model.parameters(),0.1,momentum=0) # 参数优化

for epoch in range(n_epochs):
    model.train() # 训练集
    for x,y in tr_set:
        optimizer.zero_grad() # 清空参数
        x,y = x.to(device),y.to(device)
        pred = model(x) 
        loss = criterion(pred,y)
        loss.backward()
        optimizer.step()

    model.eval() # 验证集
    toatal_loss = 0
    for x,y in dv_set:
        x,y = x.to(device),y.to(device)
        with torch.no_grad():
            pred = model(x)
            loss = criterion(pred,y)
        total_loss += loss.cpu().item * len(x)
        avg_loss = total_loss / len(dev_set.dataset)

    model.eval() # 测试集
    preds = []
    for x in tt_set:
        x  = x.to(device)
        with torch.no_grad():
            pred = model(x)
            preds.append(pred.cpu())
